[package]
name = "xml"
version = "0.1.0"
kern = "0.7.5"
publish = false
description = "XML parsing and decoding utilities for Kern"
readme = "README.md"
license = "MIT"
authors = ["softfault <givenyoung46@gmail.com>"]
repository = "https://github.com/softfault/xml-kern.git"

[lib]
root = "src/lib.rn"

[example]
roots = [
    "examples/bench_xml.rn",
]

[test]
roots = [
    "tests/smoke.rn",
    "tests/fixtures.rn",
]
